#!/bin/bash
set -e
mydir=$(dirname $(readlink -f "$0"))
source "$mydir/helpers.sh"

isEmpty SQSDATA a directory where Solr shall keep its data like the index, config core files and logs
export SQSDATA=$(readlink -f "$SQSDATA")

isEmpty ZKROOT must be either _ or a zk-root like host:port/some/path, whereby the _ lets Solr use its internal zookeeper 

initSolrFile server/resources/log4j2.xml
initSolrFile server/solr/solr.xml

export LOG4J_PROPS="$SQSDATA/config/log4j2.xml"
export SOLR_LOGS_DIR="$SQSDATA/logs"
mkdir -p "$SOLR_LOGS_DIR"
mkdir -p "$SQSDATA/index"

if [ "$ZKROOT" = "_" ]; then
  ZK=""
else
 zkhost="${ZKROOT%%/*}"
 zkchroot="/${ZKROOT##*/}"
 if ! solr zk ls "$zkchroot" -z "$zkhost" >&/dev/null; then
   solr zk mkroot "$zkchroot" -z "$zkhost"
 fi
 ZK="-z $ZKROOT"
fi

solr start -c -m 1200M \
  -a -XX:+HeapDumpOnOutOfMemoryError \
  $ZK \
  -s "$SQSDATA/config" \
  -t "$SQSDATA/index"
